Updated cutbyname to deal with parenthesis in chosen field names.

diff --git a/cutbyname b/cutbyname
--- a/cutbyname
+++ b/cutbyname
@@ -2,7 +2,7 @@
 #
 # Wrapper of cut command where one specifies the fields by name in a header line.
 #
-# Copyright (c) 2012 Matthias Cuntz - mc (at) macu (dot) de
+# Copyright (c) 2012-2020 Matthias Cuntz - mc (at) macu (dot) de
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -35,39 +35,39 @@ TMP=${TMPDIR:-"/tmp"}
 # usage
 function usage ()
 {
-  printf "\n"
-  printf "${prog} [-d delim] -f|-n list [-h] [-l num] [-st1] [file]\n"
-  printf "\n"
-  printf "Wrapper of cut command where one specifies the fields by name in a header line.\n"
-  printf "The selected columns are written to standard output.\n"
-  printf "\n"
-  printf "Input\n"
-  printf "    file            Input file. If no file argument is specified,\n"
-  printf "                    or a file argument is a single dash ('-'), cut reads from the standard input.\n"
-  printf "    -f | -n         Comma-delimited list of field names in header line.\n"
-  printf "\n"
-  printf "Options\n"
-  printf "    -d delim        Use delim as the field delimiter character instead of the tab character.\n"
-  printf "    -h              Prints this help screen.\n"
-  printf "    -l num          Field names are in line number num instead of first line.\n"
-  printf "    -s              Suppress lines with no field delimiter characters.\n"
-  printf "                    Unless specified, lines with no delimiters are passed through unmodified.\n"
-  printf "    -t              Squeeze delimiters with tr before extraction.\n"
-  printf "    -1              Remove delimiter at beginning of header line, e.g. if\n"
-  printf "                     ann  val\n"
-  printf "                    2011  0.5\n"
-  printf "\n"
-  printf "Examples\n"
-  printf "    sed 's/2002/2003/' infile | cutbyname -f 'date,co2' -d ',' | tr ',' ' ' > outfile\n"
-  printf "\n"
-  printf "Copyright (c) 2012 Matthias Cuntz - mc (at) macu (dot) de\n"
+    printf "\n"
+    printf "${prog} [-d delim] -f|-n list [-h] [-l num] [-st1] [file]\n"
+    printf "\n"
+    printf "Wrapper of cut command where one specifies the fields by name in a header line.\n"
+    printf "The selected columns are written to standard output.\n"
+    printf "\n"
+    printf "Input\n"
+    printf "    file            Input file. If no file argument is specified,\n"
+    printf "                    or a file argument is a single dash ('-'), cut reads from the standard input.\n"
+    printf "    -f | -n         Comma-delimited list of field names in header line.\n"
+    printf "\n"
+    printf "Options\n"
+    printf "    -d delim        Use delim as the field delimiter character instead of the tab character.\n"
+    printf "    -h              Prints this help screen.\n"
+    printf "    -l num          Field names are in line number num instead of first line.\n"
+    printf "    -s              Suppress lines with no field delimiter characters.\n"
+    printf "                    Unless specified, lines with no delimiters are passed through unmodified.\n"
+    printf "    -t              Squeeze delimiters with tr before extraction.\n"
+    printf "    -1              Remove delimiter at beginning of header line, e.g. if\n"
+    printf "                     ann  val\n"
+    printf "                    2011  0.5\n"
+    printf "\n"
+    printf "Examples\n"
+    printf "    sed 's/2002/2003/' infile | cutbyname -f 'date,co2' -d ',' | tr ',' ' ' > outfile\n"
+    printf "\n"
+    printf "Copyright (c) 2012-2020 Matthias Cuntz - mc (at) macu (dot) de\n"
 }
 #
 # cleanup
 function cleanup ()
 {
-  \rm -f ${TMP}/*.${pid}*
-  exit 1
+    \rm -f ${TMP}/*.${pid}*
+    exit 1
 }
 #
 # switches
@@ -84,15 +84,15 @@ rm1=0
 s=""
 while getopts "d:f:hl:n:st1" Option ; do
     case ${Option} in
-	d) delim="${OPTARG}";;
-	f) flist=${OPTARG};;
-	h) usage 1>&2; exit 0;;
-	l) nhead=${OPTARG};;
-	n) nlist=${OPTARG};;
-	s) s="-s";;
-	t) dosqueeze=1;;
-	1) rm1=1;;
-	*) printf "Error ${prog}: unimplemented option.\n";  usage 1>&2; exit 1;;
+        d) delim="${OPTARG}";;
+        f) flist=${OPTARG};;
+        h) usage 1>&2; exit 0;;
+        l) nhead=${OPTARG};;
+        n) nlist=${OPTARG};;
+        s) s="-s";;
+        t) dosqueeze=1;;
+        1) rm1=1;;
+        *) printf "Error ${prog}: unimplemented option.\n";  usage 1>&2; exit 1;;
     esac
 done
 shift $((${OPTIND} - 1))
@@ -125,39 +125,33 @@ if [[ $# -eq 1 ]]  ; then
 else
     IN="-"
 fi
+#
 # Get header
 if [[ "${IN}" == "-" ]]  ; then
     for ((i=1;i<=${nhead};i++)) ; do
-	read f
-	echo ${f} >> ${TMP}/cbn01.${pid}
+        read f
+        echo ${f} >> ${TMP}/cbn01.${pid}
     done
     h=$(tail -1 ${TMP}/cbn01.${pid})
 else
     h=$(head -${nhead} ${IN} | tail -1)
 fi
-# Remove trailing carriage return: man -Pless\ +/\/pattern bash
-# $'\r' ANSI-C coding for carriage return: https://www.gnu.org/software/bash/manual/bash.html#ANSI_002dC-Quoting
-h=${h/%$'\r'}
 #
-# separate header into vector for case of spaces in field names
-if [[ ${dosqueeze} -eq 1 ]] ; then
-    if [[ ${rm1} -eq 1 ]] ; then
-	#nh=$(echo ${h} | tr -s "${delim}" | sed "s/[^${delim}]//g" | wc -c)
-	nh=$(printf "${h}" | tr -s "${delim}" | sed "s/[^${delim}]//g" | wc -c)
+# Remove trailing carriage return from header: man -Pless\ +/\/pattern bash
+# $'\r' ANSI-C coding for carriage return:
+#    https://www.gnu.org/software/bash/manual/bash.html#ANSI_002dC-Quoting
+h=${h/%$'\r'}
+# Remove leading delimiters from header
+if [[ ${rm1} -eq 1 ]] ; then
+    if [[ ${dosqueeze} -eq 1 ]] ; then
+        h=$(echo "${h}" | tr -s "${delim}" | sed "s/[^${delim}]//g")
     else
-	#nh=$(echo "${h}" | tr -s "${delim}" | wc -c)
-	nh=$(printf "${h}" | tr -s "${delim}" | wc -c)
-    fi
-else
-    #nh=$(echo ${h} | sed "s/[^${delim}]//g" | wc -c)
-    if [[ ${rm1} -eq 1 ]] ; then
-	#nh=$(echo "${h}" | sed "s/[^${delim}]//g" | wc -c)
-	nh=$(printf "${h}" | sed "s/[^${delim}]//g" | wc -c)
-    else
-	#nh=$(echo "${h}" | wc -c)
-	nh=$(printf "${h}" | wc -c)
+        h=$(echo "${h}" | sed "s/[^${delim}]//g")
     fi
 fi
+#
+# separate header into vector to deal with spaces in field names
+nh=$(echo "${h}" | tr "${delim}" "\n" | wc -l)
 ((nh--))
 if [[ ${nh} -eq 0 ]] ; then
     printf "Error ${prog}: no delimiter found in header line.\n" 1>&2
@@ -166,28 +160,22 @@ if [[ ${nh} -eq 0 ]] ; then
 fi
 ((nh++))
 for ((i=1;i<=${nh};i++)) ; do
-    if [[ ${dosqueeze} -eq 1 ]] ; then
-	#hh[${i}]=$(echo ${h} | tr -s "${delim}" | cut -f ${i} -d "${delim}")
-	hh[${i}]=$(printf "${h}" | tr -s "${delim}" | cut -f ${i} -d "${delim}")
-    else
-	#hh[${i}]=$(echo ${h} | cut -f ${i} -d "${delim}")
-	hh[${i}]=$(printf "${h}" | cut -f ${i} -d "${delim}")
-    fi
+    hh[${i}]=$(echo ${h} | cut -f ${i} -d "${delim}")
 done
-# separate list by ascii character 1 so that we can deal with spaces in field names
+#
+# separate input variable list by ascii character 1 so that we can deal with spaces in field names
 sep=$(echo | tr '\012' '\001')
 list1=$(echo ${list} | tr "," ${sep})
 list1="${sep}${list1}${sep}"
-# Get field numbers
-k=1
+#
+# Get field numbers corresponding to field names
 clist=""
 set +e
 for ((i=1;i<=${nh};i++)) ; do
     g=$(echo "${list1}" | grep "${sep}${hh[${i}]}${sep}")
     if [[ "${g}" != "" ]] ; then
-	clist="${clist},${k}"
+        clist="${clist},${i}"
     fi
-    ((k++))
 done
 set -e
 clist=${clist#,}
@@ -200,9 +188,9 @@ fi
 # Cut input
 if [[ "${IN}" == "-" ]]  ; then
     if [[ ${dosqueeze} -eq 1 ]] ; then
-	tr -s "${delim}" < ${TMP}/cbn01.${pid} | cut -f ${clist} -d "${delim}" ${s}
+        tr -s "${delim}" < ${TMP}/cbn01.${pid} | cut -f ${clist} -d "${delim}" ${s}
     else
-	cut -f ${clist} -d "${delim}" ${s} ${TMP}/cbn01.${pid}
+        cut -f ${clist} -d "${delim}" ${s} ${TMP}/cbn01.${pid}
     fi
     rm ${TMP}/cbn01.${pid}
     IN=<&0
