Check for newer ImageMagick installations in iinvert

diff --git a/iinvert b/iinvert
--- a/iinvert
+++ b/iinvert
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Invert colours or colour channel in image using ImageMagick.
+# Invert colors or color channel in image using ImageMagick.
 #
 # Copyright (c) 2016-2017 Matthias Cuntz - mc (at) macu (dot) de
 #
@@ -24,8 +24,13 @@
 #
 # History
 # Created  Matthias Cuntz, 2016
-# Modified Matthias Cuntz, 2017 - Options -a -0
-#                               - Check for installation of ImageMagick
+# Modified Matthias Cuntz, 2017
+#     - Options -a -0
+#     - Check for installation of ImageMagick
+# Modified Matthias Cuntz, 2022
+#     - Check for newer ImageMagick installations
+#     - Renamed colour to color to conform with ImageMagick
+#
 set -e
 #
 prog=$0
@@ -34,9 +39,24 @@ pprog=$(basename ${prog})
 # --------------------------------------------------------------------------------------------------
 # Usage
 #
+# Check ImageMagick installation
+iprog=$(which magick)
+if [[ "${iprog}z" == "z" ]] ; then
+    iprog=$(which mogrify)
+    if [[ "${iprog}z" == "z" ]] ; then
+        printf "Error ${pprog}: ImageMagick (convert/mogrify) must be installed.\n\n" 1>&2
+        exit 1
+    fi
+    mprog="mogrify"
+    cprog="convert"
+else
+    mprog="magick mogrify"
+    cprog="magick convert"
+fi
+#
 function usage () {
     printf "${pprog} [-a] [-c channel] [-d dpi] [-hn] [-o outputfile] [-s colorspace] [-0] [-1] [-2] inputimage\n"
-    printf "Invert colours or colour channel in an image with ImageMagick.\n"
+    printf "Invert colors or color channel in an image with ImageMagick.\n"
     printf "\n"
     printf "Input\n"
     printf "    inputimage      Image file readable by ImageMagick.\n"
@@ -45,24 +65,24 @@ function usage () {
     printf "    -a              Do all three standard options, i.e. -0, -1, -2, giving 3 output files:\n"
     echo   '                    if not -o outputfile given: ${inputimage%.*}-0/1/2.${inputimage##*.}.'
     printf '                    if -o outputfile given: ${outputfile}-0/1/2.${inputimage##*.}.\n'
-    printf "    -c channel      Channel to invert in sepcific colour space.\n"
+    printf "    -c channel      Channel to invert in specific color space.\n"
     printf "    -d dpi          Horizontal and vertical density of the output image.\n"
     printf "    -h              Prints this help screen.\n"
     printf "    -n              Do not set output color space to sRGB.\n"
     printf "    -o outputfile   Output file. Default: change input file.\n"
-    printf "    -s colorspace   Choose colour space for inversion. Default: RGB.\n"
-    printf "                    Get possible color spaces with: convert -list colorspace.\n"
+    printf "    -s colorspace   Choose color space for inversion. Default: RGB.\n"
+    printf "                    Get possible color spaces with: ${cprog} -list colorspace.\n"
     printf "    -0              Shortcut for -s RGB, which is the default.\n"
     printf "    -1              Shortcut for -s HSL -c L.\n"
-    printf "                    Gives brighter colours than LCH colour space inversion.\n"
+    printf "                    Gives brighter colors than LCH color space inversion.\n"
     printf "    -2              Shortcut for -s LCH -c C.\n"
-    printf "                    Gives darker colours than HSL colour space inversion.\n"
+    printf "                    Gives darker colors than HSL color space inversion.\n"
     printf "\n"
     printf "Examples\n"
     printf "    ${pprog} -s LCH -c C -d 600 -o image.png image.pdf\n"
     printf "    ${pprog} -1 -d 300 image.png\n"
     printf "\n"
-    printf "Copyright (c) 2016-2017 Matthias Cuntz - mc (at) macu (dot) de\n"
+    printf "Copyright (c) 2016-2022 Matthias Cuntz - mc (at) macu (dot) de\n"
 }
 #
 # --------------------------------------------------------------------------------------------------
@@ -102,12 +122,7 @@ elif [[ $# -gt 1 ]] ; then
     usage 1>&2
     exit 1
 fi
-# Check ImageMagick installation
-iprog=$(which mogrify)
-if [[ "${iprog}z" == "z" ]] ; then
-    printf "Error ${pprog}: ImageMagick (convert/mogrify) must be installed.\n\n" 1>&2
-    exit 1
-fi
+
 #
 # Image file
 ifile="$@"
@@ -126,9 +141,9 @@ ifile="$@"
 # rm ${ifile}?.png
 if [[ ${all} -eq 0 ]] ; then
     if [[ "${ofile}z" == "z" ]] ; then
-        mogrify ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile}
+        ${mprog} ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile}
     else
-        convert ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile} ${ofile}
+        ${cprog} ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile} ${ofile}
     fi
 else
     for i in 0 1 2 ; do
@@ -142,8 +157,11 @@ else
             1) colorspace="-colorspace HSL"; channel="-channel L";;
             2) colorspace="-colorspace LCH"; channel="-channel C";;
         esac
-        convert ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile} ${outfile}
+        ${cprog} ${density} ${colorspace} ${channel} -negate ${outspace} ${density} ${ifile} ${outfile}
     done
 fi
 #
 exit 0
+
+# Test modulate: https://www.nature.com/articles/d41586-021-00263-0
+# convert $file -channel RGB -negate -modulate 100,100,200 out_$file
